# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
builds:
  - main: ./cmd/bot
    mod_timestamp: "{{.CommitTimestamp}}"
    flags: -x
    ldflags:
      - -X main.version={{.Version}}
      - -X main.builtAt={{.Now.Format "2006-01-02T15:04:05Z07:00"}}
    goos: [linux]
    goarch: [amd64]
archives:
  - format: binary
    name_template: "{{ .Binary }}"
checksum:
  disable: true
changelog:
  use: github-native
release:
  name_template: "Release {{.Tag}}"
