name: Create Release
on:
  push:
    tags:
      - "*"
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
      - name: Build
        run: go build -o energieprijzen
      - name: Extract tag name
        id: extract_tag_name
        run: echo "::set-output name=tag_name::$(echo ${GITHUB_REF#refs/tags/})"
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: energieprijzen
          generateReleaseNotes: true
          makeLatest: true
          name: Release ${{ steps.extract_tag_name.outputs.tag_name }}
