name: Create Release
on:
  push:
    tags:
      - "*"
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Test
        run: go test ./...
      - name: Build
        run: go build -o energieprijzen cmd/bot/main.go
      - name: Extract tag name
        run: echo "tag_name=$(echo ${GITHUB_REF#refs/tags/})" >> "$GITHUB_ENV"
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: energieprijzen
          generateReleaseNotes: true
          makeLatest: true
          name: Release ${{ env.tag_name }}
