name: Upgrade Templ
on: pull_request
permissions:
  contents: write
jobs:
  update-templ:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'dependabot/go_modules/github.com/a-h/templ-')
    steps:
      - uses: actions/checkout@v4
      - name: Extract versions from commit message
        id: extract_version
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          OLD_VERSION=$(echo "$TITLE" | grep -oP 'from \K\d+\.\d+\.\d+')
          NEW_VERSION=$(echo "$TITLE" | grep -oP 'to \K\d+\.\d+\.\d+')
          echo "::set-output name=old_version::$OLD_VERSION"
          echo "::set-output name=new_version::$NEW_VERSION"
      - name: Install Templ
        run: |
          cd $RUNNER_TEMP && \
          wget https://github.com/a-h/templ/releases/download/v${{ steps.extract_version.outputs.new_version }}/templ_Linux_x86_64.tar.gz && \
          tar xf templ_Linux_x86_64.tar.gz && \
          mv templ /usr/local/bin
      - name: Replace old version with new one in .devcontainer/Dockerfile
        run: |
          sed -i 's/${{ steps.extract_version.outputs.old_version }}/${{ steps.extract_version.outputs.new_version }}/' .devcontainer/Dockerfile
      - run: templ generate
      - name: Commit changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -am "Bump Templ version in Dockerfile and regenerate template Go file"
          git pull origin HEAD:${{ github.head_ref }}
          git push origin HEAD:${{ github.head_ref }}
